/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package General;

/**
 *
 * @author Lenovo
 */
// Admin.java
// Represents an administrator user

public class Admin {
    private int id;
    private String username;
    private String hashedPassword; // Store hashed password, not plain text

    // Constructor
    public Admin(String username, String hashedPassword) {
        this.username = username;
        this.hashedPassword = hashedPassword;
        // ID would typically be auto-generated by the database or set after retrieval
    }

    public Admin(int id, String username, String hashedPassword) {
        this.id = id;
        this.username = username;
        this.hashedPassword = hashedPassword;
    }

    // Getters
    public int getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public String getHashedPassword() {
        return hashedPassword;
    }

    // Setters
    // ID is often set by the database, so a setter might not always be public
    public void setId(int id) {
        this.id = id;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }

    // toString method for debugging or logging (optional)
    @Override
    public String toString() {
        return "Admin{" +
               "id=" + id +
               ", username='" + username + '\'' +
               // Avoid printing password, even if hashed, in production logs
               '}';
    }
}

